name: Lint CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Test Lint
        run: npm run lint:fix